### ISSUE TITLE
igx-column ngFor inside of igx-column-group results in duplicate columns

### ISSUE THREAD

**Issue by SkylerLutz** [IgniteUI/igniteui-angular#13123]
## Description  
Hi, I created a dynamic number of igx-columns with ngFor inside of an igx-column-group. For some unexpected reason, each column appears twice--once inside the igx-column-group and once outside of any igx-column-group. Hopefully I'm just setting it up wrong. If it turns out to be a bug, can you please backport a patch to 13.x? Thank you! 

 * igniteui-angular version: 13.2.24
 * browser: Chrome Version 113.0.5672.92 (Official Build) unknown (64-bit)

typescript:
```
public doThing() {
    this.cols = [...this.cols, 'qux']
  }

  public cols = ['baz'];
  public testData = [
    {
      foo: 'foo1',
      bar: 'bar1',
      baz: 'baz1'
    }
  ];
```
html:
```
<igx-grid [data]="testData">
  <igx-column-group header="fixed" [collapsible]="false">
    <igx-column field="foo"></igx-column>
    <igx-column field="bar"></igx-column>
  </igx-column-group>
  <igx-column-group header="dynamic" [collapsible]="false">
    <igx-column *ngFor="let c of cols" [field]="c"></igx-column>
  </igx-column-group>
</igx-grid>
<button (click)="doThing()">click me</button>
```

## Attachments  
![bug](https://github.com/IgniteUI/igniteui-angular/assets/4675572/e6a14fd3-4802-4ecd-925a-35d1bc9b098d)

**Comment by hanastasov** [comment]
Hi @SkylerLutz , we will have a look at that one and let you know once we know if it is a bug or not. If it turns out to be a bug, we woukld not be able to backport it to version 13, as it is out of support already.

**Comment by SkylerLutz** [comment]
Thanks. What major versions could the patch be applied to, and how much effort would it be to migrate to that version from 13? Thanks

**Comment by SkylerLutz** [comment]
@hanastasov any luck reproducing this issue?

**Comment by SkylerLutz** [comment]
@PlamenD95 any luck reproducing this issue?

**Comment by PlamenD95** [comment]
Hello @SkylerLutz, after some investigation I found out that the issue cannot be reproduced on later versions of IgniteUI with version 14.0.0 being the first version where the bug cannot be reproduced. 

We haven't found an explicit fix to this issue that was made in our code, so we believe that the bug was initially caused by the way Angular handles ContentChildren. It appears that in version 14 of Angular this has been resolved.

The earliest version which we currently support is 14.2.x, which is why we recommend upgrading to 14.2.x or to a later version.

You can follow the update instructions outlined here: 
[https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/update-guide](url)

I'm available in case of further questions.

**Comment by SkylerLutz** [comment]
@PlamenD95 I upgraded to 14.3.0 but I still see the issue. After following the upgrade guide, I deleted node_modules and re-ran `npm install`, and did a hard browser refresh, but still no luck. Is there another step I need to fix the issue?

**Comment by PlamenD95** [comment]
hi @SkylerLutz, thank you for pointing out the issue is still occurring, I'm re-investigating it and will update you as soon as possible

**Comment by PlamenD95** [comment]
Hello @SkylerLutz, apologies for giving you the 14.2.x version of @infragistics/igniteui-angular.
I can confirm that it's not working there. 

I have double checked with version 15.0.0 and higher and I can confirm that the ngFor works properly there and there are no duplicate columns. 

I have also double checked for any changes introduced by us to the grid.component as well as to the grid-base from here: https://github.com/IgniteUI/igniteui-angular/compare/14.2.38...15.0.0. 
I couldn't find anything relevant to the ngFor error.
This is why I still believe that changes to the way Angular itself handles ContentChildren have resolved the issue in the higher version.

Updating @infragistics/igniteui-angular to 15.0.0 or to a higher version should resolve the issue for you.

Apologies again for giving you the wrong version initially.
I'm available in case of further questions.
